image: maven:3.9.1-openjdk-11

default:
  tags:
    - shelllocal

stages:
  - test

Tests with allure:
  stage: test
  script:
    - mvn.exe clean test
    - mvn.exe allure:report allure:serve
  artifacts:
    paths:
      - target\allure-results\*