image: maven:3.9-openjdk-11

default:
  tags:
    - shelllocal

stages:
  - test

Tests with allure:
  stage: test
  script:
    - mvn clean test
    - mvn allure:report
  artifacts:
    paths:
      - target\allure-results\*