image: maven:3.9-openjdk-11

default:
  tags:
    - shelllocal

stages:
  - tests
  - allure

#Tests with allure:
#  stage: test
#  script:
#    - mvn clean test
#  artifacts:
#    when: always
#    paths:
#      - target\allure-results\*

Test add customer:
  stage: tests
  tags:
    -add-customer
  artifacts:
    when: always
    paths:
      - target\allure-results\*

Allure report:
  stage: allure
  script:
    - mvn allure:report
  when: always
    paths:
      - target\allure-results\*