image: maven:3.9.1-jdk-1.8.0_251

default:
  tags:
    - shelllocal

stages:
  - test

Tests with allure:
  stage: test
  script:
    - mvn clean test
    - mvn allure:report allure:serve
  artifacts:
    paths:
      - target\allure-results\*