image: maven:3.8-openjdk-11

default:
  tags:
    - shelllocal

stages:
  - test

Tests with allure:
  stage: test
  script:
    - C:\Program Files (x86)\maven\apache-maven-3.9.1\bin\mvn clean test
    - C:\Program Files (x86)\maven\apache-maven-3.9.1\bin\mvn allure:report allure:serve
  artifacts:
    paths:
      - target\allure-results\*